name: Build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.4
      - name: build
        run: echo Hello, Building stuff!
      - name: list files
        run: ls
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d%H%M')"
      - name: create release
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
          tag: 'Version-${{ steps.date.outputs.date }}'
        run: |
          gh release create "$tag" \
              --repo="$GITHUB_REPOSITORY" \
              --title="${GITHUB_REPOSITORY#*/} ${tag#v}" \
              --generate-notes
