name: Deploy Release

on:
  release:
    branches: [main]
    types: [published]
  workflow_dispatch:
jobs:
  download-release:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: download
        run: gh release download ${{ github.event.release.tag_name }} --output ./release
      - name: list release content
        run: ls ./release
  deployment-dev:
    if: ${{ github.event_name != 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    environment: dev
    concurrency: dev-group
    steps:
      - name: deploy
        run: echo Hello, World! Deploying to Dev
  deployment-test:
    if: ${{ github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    environment: test
    concurrency: test-group
    steps:
      - name: deploy
        run: echo Hello, World! Deploying to Test
  deployment-prod:
    needs: [deployment-test]
    runs-on: ubuntu-latest
    environment: prod
    concurrency: prod-group
    steps:
      - name: deploy
        run: echo Hello, World! Deploying to Prod

