name: Deployments Test
on:
  release:
jobs:
  deployment-dev:
    runs-on: ubuntu-latest
    environment: dev
    concurrency: dev-group
    steps:
      - name: deploy
        run: echo Hello, World! Deploying to Dev
  deployment-test:
    needs: [deployment-dev]
    runs-on: ubuntu-latest
    environment: test
    concurrency: test-group
    steps:
      - name: deploy
        run: echo Hello, World! Deploying to Test
  deployment-prod:
    needs: [deployment-test]
    runs-on: ubuntu-latest
    environment: prod
    concurrency: prod-group
    steps:
      - name: deploy
        run: echo Hello, World! Deploying to Prod

